version: '2'

services:
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  backend-discovery:
    image: 'backend-discovery:latest'
    healthcheck:
      test: "exit 0"
    build:
      context: .
    container_name: backend-discovery
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 8761:8761

  backend-product:
    image: 'backend-product:latest'
    build:
      context: .
    container_name: backend-product
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 8081:8080
      - 5432
    depends_on:
      backend-discovery:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - eureka.client.serviceUrl.defaultZone=http://backend-discovery:8761/eureka/
      - SPRING_DATASOURCE_READER_URL=jdbc:postgresql://db:5432/t_product
      - SPRING_DATASOURCE_READER_USERNAME=admin
      - SPRING_DATASOURCE_READER_PASSWORD=aDminiCom@!23
      - SPRING_DATASOURCE_WRITER_URL=jdbc:postgresql://db:5432/t_product
      - SPRING_DATASOURCE_WRITER_USERNAME=admin
      - SPRING_DATASOURCE_WRITER_PASSWORD=aDminiCom@!23
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  backend-order:
    image: 'backend-order:latest'
    build:
      context: .
#    container_name: backend-order
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - "8082-8087:8080"
      - 5432
    depends_on:
      backend-discovery:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - SERVICE_REGISTER_URI=http://backend-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/t_order
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=aDminiCom@!23
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  backend-user:
    image: 'backend-user:latest'
    build:
      context: .
    container_name: backend-user
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 8088:8080
      - 5432
    depends_on:
      backend-discovery:
        condition: service_healthy
      db:
        condition: service_healthy
    environment:
      - SERVICE_REGISTER_URI=http://backend-discovery:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/t_user
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=aDminiCom@!23
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  backend-gateway:
    image: 'backend-gateway:latest'
    build:
      context: .
    container_name: backend-gateway
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - 8080:8080
    depends_on:
      - backend-user
      - backend-product
      - backend-order
    environment:
      - SERVICE_REGISTER_URI= http://backend-discovery:8761/eureka/
      - PRODUCT_URI= http://backend-product:8080/
      - PRODUCT_ID= backend-product
      - ORDER_URI= http://backend-order:8080/
      - ORDER_ID= backend-order

  db:
    image: 'postgres-db'
    healthcheck:
      test: "exit 0"
    container_name: db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_MULTIPLE_DATABASES="t_product","t_order","t_user"
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=aDminiCom@!23
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
#  db-product-data:
#  db-order-data:
