spring:
  datasource:
    reader:
      url: jdbc:postgresql://localhost:5432/t_product
      username: admin
      password: aDminiCom@!23
    writer:
      url: jdbc:postgresql://localhost:5432/t_product
      username: admin
      password: aDminiCom@!23
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  flyway:
    baseline-on-migrate: true

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"

server:
  port: 8080

kafka:
  bootstrapAddress: localhost:29092

message:
  topic:
    name: order-transaction

logging:
  level:
    root: INFO
    com.yum: DEBUG
    com.yum.hutbot.core.datasource: DEBUG
    org:
      springframework:
        web: DEBUG
        jdbc:
          core: TRACE
