server:
  port: 8080

spring:
  application:
    name: icom-api-gateway
  cloud:
    gateway:
      routes:
        - id: ${PRODUCT_ID:backend-product}
          uri: ${PRODUCT_URI:http://localhost:8081}
          predicates:
            - Path=/v1/products/**
        - id: ${ORDER_ID:backend-order}
          uri: ${ORDER_URI:http://localhost:8081}
          predicates:
            - Path=/v1/orders/**
        - id: eureka-api
          uri: ${EUREKA_URI:http://localhost:8761/}
          predicates:
            - Path=/eureka/api/{segment}
          filters:
            - SetPath=/eureka/{segment}
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTER_URI:http://localhost:8761/eureka/}
    register-with-eureka: false
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE

