server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: ${PRODUCT_ID:backend-product}
          uri: ${PRODUCT_URI:http://localhost:8081}
          predicates:
            - Path=/v1/products/**
        - id: ${ORDER_ID:backend-order}
          uri: ${ORDER_URI:http://localhost:8081}
          predicates:
            - Path=/v1/order/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTER_URI:http://localhost:8761/eureka/}
    register-with-eureka: false
  instance:
    preferIpAddress: true
