apiVersion: apps/v1
kind: Deployment
metadata:
  name: icom-order
  labels:
    app: icom-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icom-order
  template:
    metadata:
      labels:
        app: icom-order
    spec:
      containers:
        - name: backend-order
          image: backend-order:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: postgres_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/t_order

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: icom-product
  labels:
    app: icom-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: icom-product
  template:
    metadata:
      labels:
        app: icom-product
    spec:
      containers:
        - name: backend-product
          image: backend-product:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: postgres_user
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: postgres_password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/t_product

