spring:
  application:
    name: backend-order
  datasource:
    url: jdbc:postgresql://localhost:5432/t_order
    username: admin
    password: aDminiCom@!23
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  flyway:
    baseline-on-migrate: true

kafka:
  bootstrapAddress: localhost:29092

message:
  topic:
    name: order-transaction

icom:
  services:
    product:
      url: http://127:0:0:1:8081

eureka:
  client:
    serviceUrl:
      defaultZone: ${SERVICE_REGISTER_URI:http://localhost:8761/eureka/}
