server.port: 8082
spring:
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:local}"
  application:
    name: icom-store-service
  datasource:
    url: jdbc:mysql://localhost:3306/i_store
    username: root
    password: root
  jpa:
    database: MYSQL
    openInView: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # https://docs.jboss.org/hibernate/stable/core.old/reference/en/html/configuration-optional.html
        jdbc:
          batch_size: 25
          batch_versioned_data: true
          time_zone: UTC
        order_inserts: true
        order_updates: true
        show_sql: false

  flyway:
    baseline-on-migrate: true

management:
  endpoints:
    web:
      base-path: "/"
      path-mapping:
        health: "healthcheck"

server:
  port: 8080

kafka:
  bootstrapAddress: localhost:29092

message:
  topic:
    name: order-transaction

logging:
  level:
    root: INFO
    com.yum: DEBUG
    com.yum.hutbot.core.datasource: DEBUG
    org:
      springframework:
        web: DEBUG
        jdbc:
          core: TRACE
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${SERVICE_REGISTER_URI:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    path: "/swagger.html"
